include ../../build/make_rule/compiler.mk
include ../../build/make_rule/compilepath.mk

TARGET := list0623

SRCS := $(
OBJS := 

CFLAGS := -D__ARM__ -D__LINUX_OS__
LDLFAGS := 

INCLUDE := \
	   ./include


all: $(TARGET)



clean:

