/* Generated by configure */
#include <tmmintrin.h>
int main(int argc, char **argv)
{
    (void)argc; (void)argv;
    /* BEGIN TEST: */
    __m128i a = _mm_set1_epi32(42);
    _mm_abs_epi8(a);
    (void) _mm_sign_epi16(a, _mm_set1_epi32(64));
    /* END TEST */
    return 0;
}
