/* Generated by configure */
#include <sys/slog2.h>
int main(int argc, char **argv)
{
    (void)argc; (void)argv;
    /* BEGIN TEST: */
    slog2_set_default_buffer((slog2_buffer_t)-1);
    /* END TEST */
    return 0;
}
