/* Generated by configure */
#include <immintrin.h>
int main(int argc, char **argv)
{
    (void)argc; (void)argv;
    /* BEGIN TEST: */
    // AVX
    _mm256_zeroall();
    __m256i a = _mm256_setzero_si256();
    // AVX2
    __m256i b = _mm256_and_si256(a, a);
    (void) _mm256_add_epi8(a, b);
    /* END TEST */
    return 0;
}
