/* Generated by configure */
#include <stdio.h>
#include <stdlib.h>
#ifdef __MINGW32__
#  include <winsock2.h>
#  include <ws2tcpip.h>
#else
#  include <sys/types.h>
#  include <sys/socket.h>
#  include <netdb.h>
#endif
int main(int argc, char **argv)
{
    (void)argc; (void)argv;
    /* BEGIN TEST: */
    addrinfo *res = 0;
    (void) getaddrinfo("foo", 0, 0, &res);
    freeaddrinfo(res);
    gai_strerror(0);
    /* END TEST */
    return 0;
}
