/* Generated by configure */
#include <X11/Xlib.h>
#include <X11/extensions/XInput2.h>
#include <X11/extensions/Xge.h>
#ifndef XInput_2_0
#  error Missing XInput_2_0 #define
#endif
int main(int argc, char **argv)
{
    (void)argc; (void)argv;
    /* BEGIN TEST: */
    // need XGenericEventCookie for XInput2 to work
    Display *dpy = 0;
    XEvent xevent;
    XIEvent *xievent = 0;
    XIDeviceEvent *xideviceevent = 0;
    XIHierarchyEvent *xihierarchyevent = 0;
    int deviceid = 0;
    int len = 0;
    (void) XGetEventData(dpy, &xevent.xcookie);
    XFreeEventData(dpy, &xevent.xcookie);
    (void) XIListProperties(dpy, deviceid, &len);
    /* END TEST */
    return 0;
}
