/* Generated by configure */
#ifdef __APPLE__
#  include <OpenGL/gl.h>
#else
#  define GL_GLEXT_PROTOTYPES
#  include <GL/gl.h>
#endif
int main(int argc, char **argv)
{
    (void)argc; (void)argv;
    /* BEGIN TEST: */
    glBegin(GL_TRIANGLES);
        glVertex2f(20.0f, 10.0f);
        glVertex2f(10.0f, 30.0f);
        glVertex2f(20.0f, 50.0f);
    glEnd();
    /* END TEST */
    return 0;
}
