/* Generated by configure */
#include <EGL/egl.h>
#include <bcm_host.h>
int main(int argc, char **argv)
{
    (void)argc; (void)argv;
    /* BEGIN TEST: */
    vc_dispmanx_display_open(0);
    /* END TEST */
    return 0;
}
