/* Generated by configure */
#include <xcb/xcb.h>
#include <X11/Xlib.h>
#include <X11/Xlib-xcb.h>
int main(int argc, char **argv)
{
    (void)argc; (void)argv;
    /* BEGIN TEST: */
    Display *dpy = XOpenDisplay("");
    (void) XGetXCBConnection(dpy);
    /* END TEST */
    return 0;
}
