/* Generated by configure */
#include <cups/cups.h>
int main(int argc, char **argv)
{
    (void)argc; (void)argv;
    /* BEGIN TEST: */
    cupsGetNamedDest(CUPS_HTTP_DEFAULT, NULL, NULL);  // CUPS 1.4 test
    /* END TEST */
    return 0;
}
