/* Generated by configure */
#include <xcb/xcb.h>
#include <xcb/xfixes.h>
#include <xcb/xcb_image.h>
#include <xcb/xcb_keysyms.h>
#include <xcb/xinerama.h>
#include <xcb/sync.h>
#include <xcb/randr.h>
#include <xcb/shm.h>
// This workaround can be removed for xcb-icccm > 3.8
#define class class_name
#include <xcb/xcb_icccm.h>
#undef class
int main(int argc, char **argv)
{
    (void)argc; (void)argv;
    /* BEGIN TEST: */
    int primaryScreen = 0;
    (void) xcb_connect("", &primaryScreen);
    /* END TEST */
    return 0;
}
