/* Generated by configure */
#include <xcb/xcb.h>
int main(int argc, char **argv)
{
    (void)argc; (void)argv;
    /* BEGIN TEST: */
    int primaryScreen = 0;
    (void)xcb_connect("", &primaryScreen);
    // This won't compile unless libxcb >= 1.5 which defines XCB_ATOM_PRIMARY.
    int xcbAtomPrimary = XCB_ATOM_PRIMARY;
    /* END TEST */
    return 0;
}
