/* Generated by configure */
#include <xcb/xcb.h>
#include <xcb/glx.h>
int main(int argc, char **argv)
{
    (void)argc; (void)argv;
    /* BEGIN TEST: */
    int primaryScreen = 0;
    xcb_connection_t *connection = xcb_connect("", &primaryScreen);
    xcb_generic_error_t *error = 0;
    xcb_glx_query_version_cookie_t xglx_query_cookie = xcb_glx_query_version(
            connection, XCB_GLX_MAJOR_VERSION, XCB_GLX_MINOR_VERSION);
    xcb_glx_query_version_reply(connection, xglx_query_cookie, &error);
    /* END TEST */
    return 0;
}
