### Automatic Makefile generation by 'genmake' script        ####
### Copyright, Jerry Cooperstein, Axian Inc, 2/2003 - 11/2009 ####
### License: GPLv2 ###

allofit:  userprogs

userprogs:
	@$(MAKE) \
		CFLAGS="-O2 -Wall -pedantic" \
	 lab1_fork lab2_zombie lab3_ls lab4_clone lab5_atexit lab5_decon lab5_onexit lab6_mmap lab7_daemon

clean:
	rm -rf  lab1_fork lab2_zombie lab3_ls lab4_clone lab5_atexit lab5_decon lab5_onexit lab6_mmap lab7_daemon 
