/* Generated by configure */
#include <double-conversion/double-conversion.h>
int main(int argc, char **argv)
{
    (void)argc; (void)argv;
    /* BEGIN TEST: */
    (void) double_conversion::StringToDoubleConverter::NO_FLAGS;
    /* END TEST */
    return 0;
}
