### Automatic Makefile generation by 'genmake' script        ####
### Copyright, Jerry Cooperstein, Axian Inc, 2/2003 - 11/2009 ####
### License: GPLv2 ###

allofit:  userprogs

userprogs:
	@$(MAKE) \
		CFLAGS="-O2 -Wall -pedantic" \
	 lab1_ls lab1_simple lab2_mmap lab3_symlink lab4_lock lab5_tmp lab6_inotify

clean:
	rm -rf  lab1_ls lab1_simple lab2_mmap lab3_symlink lab4_lock lab5_tmp lab6_inotify 
